### PR TITLE
VCD rebase to 2.11, plus tweaks

### PR DESCRIPTION
**Pull request by jlmorris3827**
1) Rebase to 2.11.0. For reasons I don't understand, this caused all of my changes to show up again.   Most of these changes are not new except for #2 below 
2) Split the Oauth code out of GetAuthResponse and put it into GetOauthResponse so that it can be called independently from the infra code.  This is the only actual change in this PR besides the rebase.

### CODE REVIEW

**Comment by gainsley** [comment]
Jim I don't think your local branch is up-to-date with master, that's why it's showing 4 commits to push, and you have a merge conflict. You probably need to:
git checkout master
git pull
git checkout oauth-2
git merge origin master

**Comment by jlmorris3827** [comment]
> Jim I don't think your local branch is up-to-date with master, that's why it's showing 4 commits to push, and you have a merge conflict. You probably need to:
> git checkout master
> git pull
> git checkout oauth-2
> git merge origin master

you're right, thanks, Jon.  Easier to read now.

**Review by levshvarts — APPROVED** [review]
Looks good. With our changes it will slowly diverge from the master. Are we going to just periodically sync to master from vmware branch? Or will we just stick to this version?

**Comment by jlmorris3827** [comment]
> Looks good. With our changes it will slowly diverge from the master. Are we going to just periodically sync to master from vmware branch? Or will we just stick to this version?

Thanks for the review @levshvarts !  To answer your question, we will continue to rebase periodically.  As our changes are relatively small, there have not been merge issues so far (2.10 to 2.11 was pretty painless).

**Pull request merged**
